name: Build project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    container: registry.fedoraproject.org/fedora:latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout core repo
        uses: actions/checkout@v3
        with:
          repository: loganmc10/mupen64plus-core
          path: mupen64plus-core
          ref: simple64
      - name: Update and install packages
        run: |
          dnf -y update
          dnf -y install qt6-qtwebsockets-devel SDL2-devel zlib-devel
      - name: Run build script
        run: |
          echo "#define GUI_VERSION \"a12345\"" > version.h
          mkdir build
          cd build
          qmake6 ..
          make
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Checkout core repo
        uses: actions/checkout@v3
        with:
          repository: loganmc10/mupen64plus-core
          path: mupen64plus-core
          ref: simple64
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-qt6
            mingw-w64-x86_64-gcc
      - name: Run build script
        run: |
          echo '#define GUI_VERSION "a12345"' > version.h
          mkdir build
          cd build
          msys2 -c 'qmake6 ..'
          msys2 -c 'make'
