name: Build project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: registry.fedoraproject.org/fedora:latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: simple64-gui
      - name: Checkout core repo
        uses: actions/checkout@v3
        with:
          repository: simple64/mupen64plus-core
          path: mupen64plus-core
          ref: simple64
      - name: Update and install packages
        run: |
          dnf -y update
          dnf -y install qt6-qtwebsockets-devel SDL2-devel zlib-devel cmake ninja-build
      - name: Run build script
        run: |
          cd simple64-gui
          echo "#define GUI_VERSION \"a12345\"" > version.h
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
          VERBOSE=1 cmake --build .
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          path: simple64-gui
      - name: Checkout core repo
        uses: actions/checkout@v3
        with:
          repository: simple64/mupen64plus-core
          path: mupen64plus-core
          ref: simple64
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-qt6
            mingw-w64-x86_64-gcc
      - name: Run build script
        run: |
          cd simple64-gui
          echo '#define GUI_VERSION "a12345"' > version.h
          mkdir build
          cd build
          msys2 -c 'cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..'
          msys2 -c 'VERBOSE=1 cmake --build .'
