name: Build project

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    container: quay.io/centos/centos:stream9
    steps:
      - uses: actions/checkout@v2
      - name: Checkout core repo
        uses: actions/checkout@v2
        with:
          repository: mupen64plus/mupen64plus-core
          path: mupen64plus-core
      - name: Update and install packages
        run: |
          dnf -y update
          dnf -y install qt5-qtwebsockets-devel SDL2-devel zlib-devel
      - name: Run build script
        run: |
          echo "#define GUI_VERSION \"a12345\"" > version.h
          mkdir build
          cd build
          qmake-qt5 ..
          make
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Checkout core repo
        uses: actions/checkout@v2
        with:
          repository: mupen64plus/mupen64plus-core
          path: mupen64plus-core
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-qt5
            mingw-w64-x86_64-gcc
      - name: Run build script
        run: |
          echo '#define GUI_VERSION "a12345"' > version.h
          mkdir build
          cd build
          msys2 -c 'qmake ..'
          msys2 -c 'make'
